# Generated by Django 4.1.4 on 2022-12-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
                ('precio', models.CharField(max_length=90)),
            ],
        ),
    ]
